### ISSUE TITLE
rule to switch on/off relay

### ISSUE THREAD

**Issue by kkmaslowski** [trombik/esphome-component-ping#11]
Hi. I flashed sonoff basic and I want to switch on relay if test device is responding to ping and switch off when it does not respond. How can I do that? Please provide more examples. I'm trying to power off my all multimedia devices when TV is off.

**Comment by trombik** [comment]
see https://github.com/trombik/esphome-component-ping/blob/main/config/influxdb.yaml

instead of `on_value` automation hook, use `on_value_range`.

https://esphome.io/components/sensor/index.html#on-value-range
